# Chemin par défaut pour le fichier de sortie.
output_path: "./build/project_context.txt"

# --- SÉLECTION DES FICHIERS ---

# --- SÉLECTION DES FICHIERS ---

# ÉTAPE 1: INCLUSION (prioritaire)
# Seuls les fichiers et dossiers correspondant à ces patterns seront considérés.
# Le pattern '**/*' signifie "tous les fichiers dans tous les sous-dossiers".
# Exemples :
#   - ['src/', 'tests/', 'README.md'] pour ne prendre que le contenu de 'src', 'tests' et le fichier README.
#   - ['*.py', 'requirements.txt'] pour ne prendre que les fichiers Python et le fichier requirements.
include_patterns:
  # - '**/*'
  - 'main.py'

# ÉTAPE 2: EXCLUSION
# Parmi les fichiers inclus à l'étape 1, ceux qui correspondent à ces patterns
# seront retirés.

# Filtres communs : s'appliquent PARTOUT (arbre et contenu des fichiers).
# Idéal pour exclure les dépendances, les builds, les caches, etc.
common_filters:
  - "__pycache__/"
  - "*.pyc"
  - ".git/"
  - ".venv/"
  - "venv/"
  - "node_modules/"
  - "build/"
  - "dist/"
  - ".idea/"
  - ".vscode/"

# Filtres spécifiques au contenu : N'exclut que du contenu des fichiers,
# mais le fichier/dossier APPARAÎTRA dans l'arbre.
project_only_filters:
  - ""

# Filtres spécifiques à l'arbre : N'exclut que de l'affichage de l'arbre.
# Le contenu de ces fichiers SERA INCLUS dans la sortie finale.
tree_only_filters:
  - "*.md"
  - "LICENSE"
  - ".gitignore"
  - "config.yaml"

# --- OPTIONS AVANCÉES ---

# Pour l'option --headers-only, les fonctions/classes dont le nom correspond
# à ces patterns seront incluses intégralement.
full_body_filters:
  - "main"
  - "run_app"
  - "settings"
  - "configure_*"